icon-project/loopchain

- testcase/unittest/test_util.py
temp files not found and not deleted correctly in case of `run directory is not loopchain root` .
> fixed to use absoulte path in clean_up_temp_db_files()

- loopchain/radiostation/rs_outer_service.py
- loopchain/radiostation/rs_service.py
This patch fixes two initial run problems.
1. In some environments, `RestServiceRS` will not run when we execute `loop rs`. The `time.sleep (1)` fixes this situation, but I added a TODO comment to encourage you to determine the exact cause.
2. Fixed an issue that occurs when multiple peers attempt to connect to the initialized loopchain at the same time. `__load_peer_manager_lock` locks total process of creating `PeerManager` and new peer information.
> Fix multiple leader problem when peers try to connect at a same time

- loopchain/utils/__init__.py
- `exit_and_msg` does not shut down immediately.
- Add guard codes to make sure of terminating the process.
> [LC-160] Add guard codes to make sure of terminating process

- loopchain/blockchain/exception.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/channel/channel_statemachine.py
- loopchain/configure_default.py
- loopchain/peer/block_manager.py
- loopchain/utils/loggers/configuration_presets.py
* Call state machine trigger 'vote' with unconfirmed block param.
* remove __unconfirmedBlockQueue
* Send failed vote when AddUnconfirmedBlock exception raised.
* set TIMEOUT_FOR_LEADER_COMPLAIN to 60 (1 min.)
> [LC-270] refactoring announce_unconfirmed_block to verify block_info when confirm prev block.

- loopchain/blockchain/exception.py
- testcase/unittest/test_tx_validator.py
It fixes `TransactionInvalidHashForamtError` to `TransactionInvalidHashFormatError`.
> Fix TransactionInvalidHashFormatError typo

- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_statemachine.py
**[Related commit](https://github.com/icon-project/icon-rpc-server/pull/64#issue-279009477)**
- '/api/v1/avail/peer' responses '200 OK' when the channel state machine has one
of states below: ["BlockGenerate", "Vote", "LeaderComplain", "Watch"]
> [LC-351] Edit Avail api

- loopchain/channel/channel_inner_service.py
- loopchain/peer/block_manager.py
I fix the bug that a vote of a new leader for a last unconfirmed block could be lost after rotation of leader.
I tried to add a vote of the new leader for `last_unconfirmed_block` to vote_queue in `consensus.py` when a new leader votes to a last unconfirmed block.
> [LC-379] Add a vote of a new leader for `last_unconfirmed_block` to vote_queue in `consensus.py`.

- loopchain/blockchain/blocks/block_verifier.py
- loopchain/blockchain/blocks/v0_3/block_builder.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
- Use all header properties to generate block hash
- Change temporary hash to confirmed hash
- Resign when building a new block to rehash the block.
> [LC-306] Use all header properties to generate block hash

- loopchain/blockchain/blocks/v0_3/block_verifier.py
Allow verify exception when normal block's next reps hash is empty (it is intended in v0.3 block.)
> [LC-618] Allow verify exception when normal block's next reps hash is

- loopchain/baseservice/node_subscriber.py
- loopchain/channel/channel_service.py
- setup.py
- testcase/unittest/baseservice/test_node_subscriber.py
**This is a child side (those who is requesting) between connection. (PARENT CODE: https://github.com/icon-project/icon-rpc-server/pull/106)**
> Two PRs are coupled but has no dependencies.
- Split out methods to check error response
- Split out subscribe loop into 3 parts:
1. prepare_connection: initialize properties to be in ready to connect rs_target.
2. handshake: establish connection between nodes
3. subscribe_loop: subscribe blocks and heartbeats.
- Exceptions no longer assigned and not delayed as a property, but raises immediately when something goes wrong.
- Add unit tests
> [LC-676] Refactoring NodeSubscriber

- citizen/conf/iconrpcserver_mainnet.json
- citizen/conf/iconrpcserver_testnet.json
- conf/mainnet/iconrpcserver_conf.json
- conf/testnet/iconrpcserver_conf.json
- Remove `redirectProtocol` of `ICON-RPC-Server` in mainnet, testnet, citizen dist configs.
**_NOTE_**: Redirection URL (the url that txs are expected to be sent to, if the node is citizen) is supplied by `Loopchain`, and no more allowed for the option to be set in `ICON-RPC-Server`.
> caused: https://github.com/icon-project/icon-rpc-server/pull/105
> [LC-624] Remove `redirectProtocol` in configs

- loopchain/blockchain/invoke_result.py
- testcase/unittest/blockchain/test_invoke_result.py
- Create `InvokeRequest`, `InvokeResult` and `InvokeResultPool`.
> - There are no dependencies between a vote creator and a caller of invoke function.
> - `stateHash` and `receiptHash` must be included in `BlockVote`
> - which means invoke result must be cached and it can be shared between a vote creator and a caller of invoke.
- InvokeRequest: 
- Wrapped data to be sent to ICON-Service.
- Provides `serialize` to convert itself as dict.
- InvokeResult: 
- Wrapped data of invoke result, returning as a result of invoke function.
- InvokeResultPool: 
- Manages `InvokeResult`
- Prunes expired (already committed) `InvokeResult`s.
> [LC-937] InvokeResult and its pool

- loopchain/blockchain/votes/v1_0/__init__.py
- loopchain/blockchain/votes/v1_0/vote.py
- loopchain/blockchain/votes/v1_0/vote_factory.py
- testcase/unittest/blockchain/test_invoke_result.py
- testcase/unittest/blockchain/votes/v1_0/test_vote.py
- testcase/unittest/blockchain/votes/v1_0/test_vote_factory.py
**(Will be resolved after #506 is resolved)**
- Add VoteFactory, which creates Vote 1.0 and its none & lazy votes.
- Implements [LFT](https://github.com/icon-project/LFT2) `VoteFactory`
- Remove height info from Vote 1.0
- LFT does not use blockHeight of `BlockVote`
> [LC-939] Add VoteFactory 1.0

- loopchain/blockchain/blockchain.py
- loopchain/channel/channel_inner_service.py
- loopchain/configure_default.py
- loopchain/utils/__init__.py
- loopchain/utils/loggers/configuration.py
- loopchain/utils/loggers/configuration_others.py
- loopchain/utils/loggers/configuration_presets.py
- requirements.txt
- Remove dependency: `fluent-logger`
- Fluentd is no longer used in Loopchain.
- Resolve conflict of the dependencies between Loopchain and ICON-Service (on `msgpack`)
> [LC-947] Remove dependency: fluent-logger

- loopchain/blockchain/types.py
- loopchain/blockchain/votes/v1_0/vote.py
- loopchain/blockchain/votes/v1_0/vote_factory.py
- testcase/unittest/blockchain/blocks/v1_0/test_block_factory.py
- testcase/unittest/blockchain/test_invoke_result.py
- testcase/unittest/blockchain/votes/v1_0/test_vote.py
- Add `consensus_id` to Vote 1.0
> This param is mandatory. Related PR: https://github.com/icon-project/LFT2/pull/27
- Edit `Block.prevStateHash` to `Block.stateHash`
> The state hash in a block indicates **current status of the block before txs not being executed**.
> [LC-973] Edit params of Block & Vote 1.0 (consensus_id, stateHash)

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/epoch.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
- testcase/unittest/test_message_queue.py
- `ChannelInnerService` has `BlockManager` and the only reason is to use `get_tx_queue`.
- `Epoch` is alose bound to `BlockManager` due to `tx_queue`
- `BlockFactory` needs `tx_queue` to get Txs in Block.
- 🤯 ...
- Supply `AgingCache(tx_queue)` where it is needed to decouple with `BlockManager`
> [LC-995] Inject AgingCache(tx_queue)

- loopchain/blockchain/blockchain.py
- loopchain/consensus/runner.py
- #517 makes a node to invoke genesis block 1.0
- Invoke succeeds but state is not changed. (Tx result is not applied to state DB)
- `BlockChain.add_block` has a flag named `need_to_score_invoke`, which enables score_invoke **AND** write_precommit_state.
- Loopchain 3.0 does not supply this flag as true due to invoking block outside of `BlockChain.add_block`, so avoids calling `write_precommit_state`.
> [LC-991] Write precommit state after Block 1.0

- loopchain/blockchain/blocks/v1_0/block_factory.py
- loopchain/blockchain/blocks/v1_0/block_verifier.py
- loopchain/blockchain/invoke_result.py
- loopchain/channel/channel_service.py
- testcase/unittest/blockchain/blocks/v1_0/test_block_factory.py
- testcase/unittest/blockchain/conftest.py
- testcase/unittest/blockchain/test_invoke_result.py
- testcase/unittest/blockchain/votes/v1_0/test_vote_factory.py
- Add PreInvokeResponse: Represent a data returned from IS PreInvoke
- No dependency of `InvokeData` to PreInvoke function when `BlockFactory.create_data`
- Replace mocked PreInvoke method (calling PreInvoke method actually)
- Change temporary name: query -> pre_invoke
- **and.. Always be with tests.**
> [LC-954] Call PreInvoke

- loopchain/channel/channel_inner_service.py
- loopchain/consensus/runner.py
- loopchain/peer/peer_outer_service.py
- testcase/unittest/channel/test_inner.py
- testcase/unittest/peer/test_outer.py
~(WIP: resolved after #559)~
- if the node requested `BlockHeightRequest`, receive it first then response in other gRPC protocol `BlockHeightResponse`
> [LC-1034] Handle requestHeight for Consensus Sync

- .github/workflows/citizen.yml
- .github/workflows/unit_test.yml
- Makefile
- setup.py
Dependent libraries can be updated patch version.
This should not be hotfixed by dependent libraries.
And, this `hotfix` PR just update `Makefile` without update version.
- compatible version with iconservice 1.7.0, iconrpcserver 1.5.0
> Update requires compatible on Makefile

- loopchain/peer/block_manager.py
Fix typo.
- Issue : The name of variable is different from the one in the configure file.
Remove unnecessary code line.
> [LC-1017] fix typo and remove unnecessary code line

- loopchain/consensus/runner.py
`Invoke` may not be execute in case of Consensus Sync in the scenario below:
- My node is turned off, so that I didn't participate in consensus process.
- Get a block and its votes from another node.
- Pass them to LFT
- RoundEnd with success
- Try to write committed block
- Raises write precommit block error!
- The requested votes are enought to confirm the block
- And it doesn't need my vote to commit it
- And Consensus engine skips its verification
- And Invoke on my node is also skipped.
- Do invoke before commit if not invoked
> [LC-1041] Do Invoke before commit if not

- loopchain/blockchain/blockchain.py
- loopchain/channel/channel_inner_service.py
- loopchain/consensus/runner.py
- `BlockHeightRequest` now triggers to return highest block height, contains `last_unconfirmed_block`
- `BlockRequest`now triggers to return highest block, contains `last_unconfirmed_block`
- Update BlockChain.last_unconfirmed_block in receiving or broadcasting any block.
- Nodes need to exchange informations each other, not only known (committed) info, but unknown (needs to be voted) info!
> [LC-1042] Update last_unconfirmed_block on LFT consensus

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/invoke_result.py
- loopchain/consensus/runner.py
- testcase/unittest/blockchain/test_invoke_result.py
- testcase/unittest/blockchain/votes/v1_0/test_vote_factory.py
- Use **`Blockchain.__invoke_results`** to remove confirmed transactions.
- In loopchain 3.0, the class who invokes does not record invoke result
- In under 3.0, invoked result recored temporarely under `Blockchain.__invoke_results`
- when confirmed txs are written, check each txs in that var, to pop out from AgingCache (unconfirmed transaction queue).
> So I make `InvokePool` to store required values like what current consensus engine does.
> [LC-1046] Remove unconfirmed transactions after committed

- loopchain/consensus/runner.py
- Broadcast Block (or Vote) again and again
Suppose that network malfunction happened. then some of nodes cannot receive necessary informations to run normally.
To avoid this situation, leader or validators must send required infos in repeat so that other network-malfunctioning nodes can receive them..
> [LC-1044] Repeat broadcast my Block or Vote

- loopchain/channel/channel_inner_service.py
We support API to get block receipts at once. (API V3)
reference API [Klaytn getBlockReceipts](https://docs.klaytn.com/bapp/sdk/caver-js/v1.4.1/api-references/caver.klay/block#getblockreceipts)
```json
// Request 1 - get last block receipts
{
"jsonrpc": "2.0",
"method": "icx_getBlockReceipts",
"id": 1234
}
// Request 2 - get block receipts by hash
{
"jsonrpc": "2.0",
"method": "icx_getBlockReceipts",
"id": 1234,
"params": {
"hash": "0x6d4a4dbb950152050684eef5d0e228b8a31cae7afd37d9760b79312305008977"
}
}
// Request 3 - get block receipts by height
{
"jsonrpc": "2.0",
"method": "icx_getBlockReceipts",
"id": 1234,
"params": {
"height": "0x4"
}
}
// Response - success
{
"jsonrpc": "2.0",
"result": [
{
"txHash": "4b9afccf0ce595fc67fd84959d8ff3107aad2e78ea418d8e115d39dbb5ddf683",
"blockHeight": …
```
> support get_blockReceipts API

- requirements.txt
- upgrade websockets to version 9.1 or later
> [IS-1378] fixed security alert
