- run_loopchain.sh
radiostation address changed `bicon.net.solidwallet.io` to`cicon.net.solidwallet.io`
> change radiostation address to cicon.net.solidwallet.io

- loopchain/channel/channel_inner_service.py
- v3 getBlock method problem
-  channel_inner_service‌ returned block hash as `Hash32`
> [LC-81] Block Version System - Bug Fix

- loopchain/channel/channel_service.py
- apply subscribe event to rest call (not to keep waiting in await syntax)
> [LC-107] apply subscribe event to rest call

- loopchain/baseservice/node_subscriber.py
- loopchain/channel/channel_inner_service.py
Do not merge until current develop (with block versioning) is ready to merge to master.
> [hotfix/LC-114] hotfix to prevent conflicts in develop merge

- conf/develop/iconrpcserver_conf.json
- conf/develop/iconservice_conf.json
* Change log level to prevent excessive stdout in performance tests.
> [LC-102] change log level of iconservice and iconrpcserver to warning

- loopchain/utils/__init__.py
> [LC-77] fix bug in generate_url

- loopchain/baseservice/peer_manager.py
- loopchain/consensus/acceptor.py
- loopchain/consensus/proposer.py
- loopchain/container/common_service.py
- loopchain/peer/block_manager.py
- loopchain/peer/peer_outer_service.py
- loopchain/radiostation/rs_admin_service.py
- loopchain/radiostation/rs_outer_service.py
- loopchain/radiostation/rs_service.py
- remove all comments: Changing the import location will cause a pickle error."
- optimized import orders
> [LC-198] Remove pickle comments

- loopchain/channel/channel_statemachine.py
repeat broadcast complain message while in state LeaderComplain.
> [LC-224] repeat broadcast complain message while in state LeaderComplain.

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/__init__.py
- loopchain/blockchain/blocks/block_prover.py
- loopchain/blockchain/blocks/v0_1a/__init__.py
- loopchain/blockchain/blocks/v0_1a/block_prover.py
- loopchain/blockchain/blocks/v0_3/__init__.py
- loopchain/blockchain/blocks/v0_3/block_builder.py
- loopchain/blockchain/blocks/v0_3/block_prover.py
- loopchain/channel/channel_statemachine.py
- testcase/unittest/test_block.py
- `get_proof` - It will return proof of target hash. The proof is a list consisting of leaves of merkle tree.
- `get_proof_root` - It will return root of merkle tree.
- `prove` - It will return True if the proof as a parameter is valid for target hash and root hash.
> [LC-185] Add `BlockProver`

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v0_3/block_prover.py
- loopchain/blockchain/transactions/genesis/transaction_serializer.py
- loopchain/channel/channel_inner_service.py
> [LC-186] Block Proof API

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/block_versioner.py
- loopchain/blockchain/blocks/v0_3/block.py
- loopchain/blockchain/blocks/v0_3/block_builder.py
- loopchain/blockchain/blocks/v0_3/block_serializer.py
- loopchain/blockchain/blocks/v0_3/block_verifier.py
- loopchain/blockchain/types.py
- loopchain/channel/channel_service.py
- testcase/unittest/test_block.py
- Change properties of Block to lower camel case.
- Change format of Block properties.
- Modify header properties used in generate block hash.
> [LC-162] Rename Block Properties

- loopchain/peer/block_manager.py
fix No leader in epoch when node start.
> [LC-275] fix No leader in epoch when node start.

- loopchain/blockchain/epoch.py
- loopchain/configure_default.py
- loopchain/peer/consensus_siever.py
Check tx.timestamp by ALLOW_TIMESTAMP_BOUNDARY_SECOND_IN_BLOCK before add it to block.
> [LC-261] check tx.timestamp by ALLOW_TIMESTAMP_BOUNDARY_SECOND_IN_BLOCK

- loopchain/baseservice/slot_timer.py
- loopchain/channel/channel_inner_service.py
- loopchain/configure_default.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
Fixed the time delay until tx was confirmed
> [LC-287] Fixed the time delay until tx was confirmed

- loopchain/baseservice/slot_timer.py
- loopchain/baseservice/timer_service.py
- loopchain/blockchain/epoch.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/launcher.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- loopchain/peer/peer_outer_service.py
* Add start method to block generator timer in consensus.
* Add round into epoch.
* Make new epoch after block sync. And Allow add complain when my epoch has same height with complain message. If the epoch height is lower than the message, execute block sync.
> [LC-291] Show round in epoch for debug.

- loopchain/statemachine/statemachine.py
- testcase/unittest/test_statemachine.py
Modify statemachine for statemachine can support multiple instance
Before code method __init__  adjust to class
After __init__ adjust to instance
> Modify statemachine for statemachine can support multiple instance

- loopchain/blockchain/blocks/block_builder.py
- loopchain/blockchain/blocks/block_verifier.py
- loopchain/blockchain/transactions/transaction_builder.py
- loopchain/blockchain/transactions/transaction_verifier.py
- loopchain/crypto/signature.py
- loopchain/peer/consensus_siever.py
- testcase/unittest/test_block.py
There are inline signature code in Block and Transaction.
I replaced it with Signer and SignVerifier.
> [LC-372] Replace inline signature code with Signer and SignVerifier.

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v0_3/__init__.py
- loopchain/blockchain/blocks/v0_3/block.py
- loopchain/blockchain/blocks/v0_3/block_builder.py
- loopchain/blockchain/blocks/v0_3/block_prover.py
- loopchain/blockchain/blocks/v0_3/block_serializer.py
- loopchain/blockchain/blocks/v0_3/block_verifier.py
- loopchain/blockchain/candidate_blocks.py
- loopchain/blockchain/epoch.py
- loopchain/blockchain/votes/v0_1a/vote.py
- loopchain/blockchain/votes/v0_1a/votes.py
- loopchain/blockchain/votes/votes.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- testcase/unittest/test_block.py
> [LC-273] Apply new vote.

- loopchain/baseservice/node_subscriber.py
- loopchain/blockchain/candidate_blocks.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
> [LC-383] Merge Block 0.3 to develop

- requirements.txt
- Prevent python version diverging
[related](https://github.com/icon-project/icon-rpc-server/pull/70)
> [LC-377] update requirements.txt

- loopchain/blockchain/blockchain.py
> [LC-408] Remove used confirm_info

- .gitignore
- loopchain/baseservice/broadcast_scheduler.py
- loopchain/baseservice/peer_manager.py
- loopchain/baseservice/peer_object.py
- loopchain/blockchain/candidate_blocks.py
- loopchain/blockchain/epoch.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_property.py
- loopchain/channel/channel_service.py
- loopchain/configure_default.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- loopchain/peer/peer_inner_service.py
- loopchain/peer/peer_outer_service.py
- loopchain/peer/peer_service.py
- loopchain/protos/loopchain.proto
- loopchain/radiostation/rs_admin_service.py
- loopchain/radiostation/rs_outer_service.py
- loopchain/radiostation/rs_service.py
- loopchain/rest_server/rest_server_rs.py
this PR pending by (https://github.com/icon-project/loopchain/pull/224).
* remove group_id
* add LOAD_PEERS_FROM_IISS option.
> [LC-386] remove group_id and add LOAD_PEERS_FROM_IISS option

- loopchain/blockchain/blocks/v0_3/block_prover.py
- loopchain/channel/channel_service.py
- loopchain/peer/consensus_siever.py
- Fix not being able to find prev vote.
- switch the order of init_network and ready_to_height_sync
- Apply removing blockHash to block prover on receipt
> [LC-412] Issues caused by merging Block(0.3) and Prep list

- loopchain/baseservice/tx_item_helper.py
- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/block_verifier.py
- loopchain/blockchain/blocks/v0_1a/block_serializer.py
- loopchain/blockchain/blocks/v0_3/block_serializer.py
- loopchain/blockchain/epoch.py
- loopchain/blockchain/transactions/transaction.py
- loopchain/blockchain/transactions/transaction_builder.py
- loopchain/blockchain/transactions/transaction_serializer.py
- loopchain/blockchain/transactions/transaction_verifier.py
- loopchain/blockchain/transactions/transaction_versioner.py
- loopchain/blockchain/transactions/v3_issue/__init__.py
- loopchain/blockchain/transactions/v3_issue/transaction.py
- loopchain/blockchain/transactions/v3_issue/transaction_serializer.py
- loopchain/blockchain/transactions/v3_issue/transaction_verifier.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- testcase/unittest/test_block.py
- testcase/unittest/test_crypto.py
- testcase/unittest/test_transaction.py
> [LC-274] Issue transaction

- conf/develop/iconservice_conf.json
- loopchain/peer/consensus_siever.py
[LC-494] Remove duplicate code from __add_block and wait_for_vote
[LC-494]: https://icon-project.atlassian.net/browse/LC-494
> [LC-494] Remove duplicate code from __add_block and wait_for_vote

- loopchain/launcher.py
* parse unknown argument as a quick command if it's possible.
> [LC-501] parse unknown argument as a quick command if it's possible.

- conf/develop/iconservice_conf.json
- loopchain/baseservice/node_subscriber.py
- loopchain/baseservice/peer_manager.py
- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/block_verifier.py
- loopchain/blockchain/blocks/v0_3/block.py
- loopchain/blockchain/blocks/v0_3/block_builder.py
- loopchain/blockchain/blocks/v0_3/block_serializer.py
- loopchain/blockchain/blocks/v0_3/block_verifier.py
- loopchain/blockchain/merkle/merkle_tree.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- testcase/unittest/test_block.py
Block 0.3
- Add `nextRepsHash` attribute
> [LC-491] Add `nextRepsHash`

- Makefile
> Fix test target

- loopchain/blockchain/blockchain.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
[LC-511] bugfix, set confirm_prev_block True while its version is 0.1a. (v0.3 doesn't use it)
[LC-511]: https://icon-project.atlassian.net/browse/LC-511
> [LC-511] bugfix, set confirm_prev_block True while its version is 0.1a.

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/votes/v0_1a/votes.py
> [LC-551] set prevBlockValidators value with ids from votes

- loopchain/configure_default.py
remove tbears from ICON_VERSIONS
> [LC-472] remove tbears from ICON_VERSIONS

- loopchain/baseservice/lru_cache.py
- loopchain/blockchain/blockchain.py
add lru_cache for find method of store to improve performance.
* add lru-cache to find_preps functions of blockchain
> [LC-548] add lru_cache for find method of store to improve performance.

- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
unrecorded_block broadcast stop when last block has reached a sufficient height.
> [LC-632] unrecorded_block broadcast stop when last block has reached a

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/epoch.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
https://icon-project.atlassian.net/browse/LC-631
> [LC-631] get_next_leader with specific block

- loopchain/blockchain/exception.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
* remove NotNeedToWaitForVotes.
* get next leader with last_block in set_peer_type_in_channel instead
latest_block.
> [LC-639] remove NotNeedToWaitForVotes.

- loopchain/blockchain/blockchain.py
- loopchain/peer/block_manager.py
Fix mismatch of a parameter in `confirm_prev_block()` for `find_preps_addresses_by_roothash()`.
> [LC-650] Fix mismatch of a parameter.

- loopchain/baseservice/broadcast_scheduler.py
- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v0_1a/block.py
- loopchain/blockchain/blocks/v0_3/block.py
- loopchain/blockchain/blocks/v0_3/block_verifier.py
- loopchain/blockchain/candidate_blocks.py
- loopchain/blockchain/epoch.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/channel/channel_statemachine.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- loopchain/peer/peer_outer_service.py
- loopchain/peermanager/peer_list_data.py
- loopchain/peermanager/peer_manager.py
- loopchain/protos/loopchain.proto
- testcase/unittest/test_candidate_blocks.py
- testcase/unittest/test_channel_statemachine.py
check block is unrecorded with block header values instead AnnounceUnrecordedBlock message.
> [LC-667] Make Unrecorded Block type with special values.

- loopchain/baseservice/node_subscriber.py
- testcase/unittest/baseservice/test_node_subscriber.py
AsyncMethod is not secured from Exceptions, which means raise exception INSIDE `node_ws_Publish..` method may crash entire NodeSubscriber Future steps.
> [LC-676] Fix make exception raised not in publish method.

- loopchain/baseservice/slot_timer.py
- loopchain/blockchain/blockchain.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
do reset_leader timing in only three cases.
1. in consensus loop (if node is a leader)
2. in add_block (if node is not a leader)
3. in add_complain (when 'leader complain' situation.)
> [LC-732] do not reset leader in vote (of block manager)

- loopchain/peer/block_manager.py
Handling the exception on first vote is None
> [LC-761] Select valid vote not first vote.

- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_statemachine.py
- loopchain/configure_default.py
- loopchain/peer/block_manager.py
- loopchain/peer/peer_inner_service.py
- loopchain/peer/peer_outer_service.py
- loopchain/peer/peer_service.py
* Do caching peer status with lru_cache not status_cache in peer_service.
* Add nid to '/api/v1/status/peer'.
> [LC-774] Add nid to '/api/v1/status/peer'.

- loopchain/baseservice/stub_manager.py
- loopchain/channel/channel_inner_service.py
- loopchain/peer/peer_outer_service.py
- loopchain/protos/loopchain.proto
- loopchain/protos/message_code.py
* remove message_code.Request.status and its handler. 
* remove GetScoreStatus in gRPC interface.
> [LC-799] remove message_code.Request.status and its handler.

- README.md
Added an ICON badge in README.md
Fix it again in the develop branch
> Add ICON badge

- requirements.txt
modify requirements to support higher version of plyvel and earlgrey.
> [LC-890] modify requirements.

- loopchain/app/app.py
- loopchain/baseservice/node_subscriber.py
- loopchain/baseservice/slot_timer.py
- loopchain/baseservice/timer_service.py
- loopchain/blockchain/blocks/block_builder.py
- loopchain/blockchain/blocks/block_serializer.py
- loopchain/blockchain/blocks/v1_0/__init__.py
- loopchain/blockchain/blocks/v1_0/block_builder.py
- loopchain/blockchain/blocks/v1_0/block_serializer.py
- loopchain/blockchain/epoch.py
- loopchain/blockchain/exception.py
- loopchain/channel/channel_service.py
- loopchain/channel/channel_statemachine.py
- loopchain/launcher.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
When `ConsensusChanged` is raised new consensus has to work.
> [LC-873] Modified structure for new consensus

- loopchain/blockchain/blocks/v1_0/__init__.py
- loopchain/blockchain/blocks/v1_0/block.py
- testcase/unittest/blockchain/blocks/v1_0/test_block.py
- Add Block 1.0 implements [LFT](https://github.com/icon-project/LFT2) Data Interface.
> [LC-886] Add Block 1.0

- loopchain/blockchain/epoch3.py
- testcase/unittest/blockchain/test_epoch.py
- Add Epoch for loopchain3.0 which implements [LFT](https://github.com/icon-project/LFT2) Epoch interface.
> [LC-930] Add Epoch

- loopchain/blockchain/blocks/v1_0/__init__.py
- loopchain/blockchain/blocks/v1_0/block.py
- loopchain/blockchain/blocks/v1_0/block_builder.py
- loopchain/blockchain/blocks/v1_0/block_factory.py
- loopchain/blockchain/blocks/v1_0/block_verifier.py
- loopchain/store/key_value_store_plyvel.py
- testcase/unittest/blockchain/blocks/v1_0/test_block_factory.py
- testcase/unittest/blockchain/conftest.py
**(Will be resolved after #507 is resolved)**
- Add BlockFactory, which creates Block 1.0 and its none & lazy one.
- Implements [LFT](https://github.com/icon-project/LFT2) `BlockFactory`
> [LC-943] Add BlockFactory 1.0

- loopchain/peer/block_manager.py
Fix.
- Peers Can't sync same block height of leader node.
> [LC-696] fix logical error that It can't sync same block height of leader node

- loopchain/blockchain/blockchain.py
- loopchain/channel/channel_inner_service.py
- loopchain/configure_default.py
- loopchain/utils/__init__.py
- loopchain/utils/loggers/configuration.py
- loopchain/utils/loggers/configuration_others.py
- loopchain/utils/loggers/configuration_presets.py
- requirements.txt
- Apply #508 into `develop3.0`
> [LC-947] Remove dependency: fluent-logger (3.0)

- loopchain/blockchain/blocks/v1_0/block_factory.py
- testcase/unittest/blockchain/blocks/v1_0/test_block_factory.py
- testcase/unittest/blockchain/conftest.py
- testcase/unittest/blockchain/test_invoke_result.py
- Implement LazyBlock & NoneBlock
> [LC-985] Implement LazyBlock & NoneBlock

- docs/8. diagram/state_machine_in_siever.wsd
> [LC-928] Update ChannelStateMachine diagram (3.0)

- README.md
> [LC-997] add lgtm badge about code quility

- .github/workflows/unit_test.yml
- Run unit test CI from Jenkins to GitHub Actions
> [LC-443] Unit test at Github Actions

- .github/workflows/unit_test.yml
(Previous: https://github.com/icon-project/loopchain/pull/279)
~(#537 should be merged first)~
- Apply #525 into develop3.0
> [LC-443] Unit test at Github Actions (3.0)

- loopchain/blockchain/votes/v1_0/vote.py
- loopchain/blockchain/votes/v1_0/vote_factory.py
- testcase/unittest/blockchain/test_invoke_result.py
- testcase/unittest/blockchain/votes/v1_0/test_vote_factory.py
-  Add missed param to Vote 1.0 (height)
> [LC-986] Add missed param to Vote 1.0 (height)

- loopchain/blockchain/blocks/v1_0/__init__.py
- loopchain/blockchain/blocks/v1_0/block.py
- loopchain/blockchain/blocks/v1_0/block_builder.py
- loopchain/blockchain/blocks/v1_0/block_serializer.py
- loopchain/channel/channel_inner_service.py
- testcase/unittest/blockchain/blocks/v1_0/test_block_serializer.py
Will be resolved after #532 is merged
> [LC-987] (+De)serialize Vote & Block 1.0

- loopchain/blockchain/blockchain.py
- loopchain/channel/channel_inner_service.py
- testcase/unittest/test_blockchain.py
V2 Api : ic_getTransactionByAddress 
- currently, It is not supported.
It delete code about icx_getTransactionByAddress.
> [LC-1001] remove code about icx_getTransactionByAddress

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v1_0/block.py
- loopchain/blockchain/epoch3.py
- loopchain/blockchain/invoke_result.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/consensus/runner.py
- loopchain/peer/block_manager.py
(Possible relation: #510 )
- Do Genesis Invoke
> [LC-963] Run LFT as Single Node (From Genesis Invoke)

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v1_0/block_factory.py
- loopchain/blockchain/epoch.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- testcase/unittest/blockchain/test_epoch_legacy.py
- testcase/unittest/test_signature_verify.py
- testcase/unittest/test_tx_message.py
(Resolve WIP status after #536 )
- Epoch has no reason to contain BlockChain and BlockManager
- They are too bloated and make LFT integration process more harder.
- Create constructor to remove outside dependencies. (epoch-BlockChain, epoch-BlockManager)
- Add tests to show `Epoch`'s original duty.
- Minor fixes
- import violations
-
> [LC-1003] Remove dependencies (Epoch)

- loopchain/blockchain/blocks/v1_0/block_factory.py
- loopchain/channel/channel_service.py
- loopchain/store/key_value_store_plyvel.py
Can not execute `icx_sendTransaction` because of:
- Tx verification failed (uniqueness check)
- NID is not set
- Pass `BlockChain` to `BlockFactory`, not `KeyValueStore`
- Set NID right after Genesis Invoke
> [LC-1010] Fix icx_sendTransactions failure after genesis invoke

- loopchain/blockchain/blockchain.py
- loopchain/channel/channel_service.py
- loopchain/channel/channel_statemachine.py
- loopchain/consensus/runner.py
- loopchain/peer/block_manager.py
- loopchain/peer/consensus_siever.py
- Node restores Block 1.0 if DB exists
1. ... do `BlockSync`.
1. Check current last block version when exiting `BlockSync`.
1. Go to State `Consensus` if Block is 1.0.
1. Initialze LFT engine with Block 1.0
> [LC-994] Rebuild Block 1.0

- loopchain/blockchain/backup_maanger.py
- loopchain/blockchain/backup_manager.py
- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/block_serializer.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/launcher.py
- loopchain/peer/block_manager.py
- loopchain/utils/__init__.py
- Distinguish Consensus essential data.
- The node must be able to request and deliver consensus essential data.
- Organize additional items for background sync and fast start
- Separate essential data and check normal operation of existing node using separated data
- Requesting essential data with cli to create backup db (loopchain_tools)
> [LC-1000] Distinguish Consensus essential data and Create backup db.

- loopchain/protos/loopchain.proto
- Add new gRPC protocols (2 messages and 3 protocols)
> [LC-1031] Additional gRPC protos for Consensus Sync

- loopchain/channel/channel_inner_service.py
- loopchain/peer/peer_outer_service.py
~(resolved after #560 )~
- Handles `BlockRequest`
> [LC-1035] Handle BlockRequest for Consensus Sync

- .github/workflows/citizen.yml
- .github/workflows/unit_test.yml
- Fix broken tests.
> This problem may be caused from other dependencies.
> Patch first into develop3.0
> [LC-1038] Fix broken CI

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v1_0/block_factory.py
- loopchain/channel/channel_inner_service.py
- loopchain/consensus/runner.py
- Runnable loopchain 3.0 between multiple nodes (from genesis only)
> [LC-972] Multi Node from Genesis

- loopchain/blockchain/blockchain.py
- loopchain/blockchain/blocks/v1_0/block.py
- loopchain/blockchain/votes/v1_0/vote_factory.py
- loopchain/consensus/runner.py
- Fix validator set of Block comes after Genesis (height 1)
- Finalize Round if all of votes (regardless Lazy or None) gathered.
- Event RoundEnd (both failure and success) should raise round number, except change epoch (in the another PR)
> [LC-1040] RoundEnd in case of Lazy/None Votes reached to consensus

- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/consensus/runner.py
- testcase/unittest/test_message_queue.py
"event_simulator" controlled by regarding LFT Source code.
> [LC-1037] change raise event logic about received unconfirmed block and vote on LFT version

- loopchain/baseservice/node_subscriber.py
- loopchain/channel/channel_service.py
- loopchain/peer/block_sync.py
handle log print exception about traceback
remove retry_history
> IS-1308: handle log print exception about traceback

- loopchain/peer/block_sync.py
related PR : #625 
[invalid code](https://github.com/icon-project/loopchain/pull/625/files#diff-ebf8c58f0deb32d03618011cc8f637186efa0e0d0a595259a4bbc157854c8f16R715-R719)
> [IS-1379] remove invalid code

- loopchain/launcher.py
- loopchain/utils/command_arguments/__init__.py
- convert pem, der to json keystore
> [IS-1832] add command to convert key

- loopchain/baseservice/node_subscriber.py
- loopchain/baseservice/rest_client.py
- loopchain/channel/channel_inner_service.py
- loopchain/channel/channel_service.py
- loopchain/peer/peer_inner_service.py
- loopchain/scoreservice/icon_inner_service.py
- shutdown websocket, aio-pika before cancel tasks
> [IS-1385] resolve stuck when cancelling asyncio tasks
